version: '3.7'

services:
  firestore:
    image: google/cloud-sdk:latest
    command: gcloud beta emulators firestore start --host-port=firestore:8080
    ports:
      - "8080:8080"
    networks:
      - database_network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - database_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - database_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    networks:
      - database_network

networks:
  database_network:
    driver: bridge